
####################################################################################
# Generated by Vivado 2022.2 built on 'Fri Oct 14 04:59:54 MDT 2022' by 'xbuild'
# Command Used: write_xdc -force /home/awhitbe1/LDMX_fw/zCCM_kria/constrs_1.xdc
####################################################################################


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
